In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("telecom_data.csv")

In [3]:
df.head()

Customer ID Churn Label  Account Length (in months)  Local Calls  \
0   4444-BZPU          No                           1            3   
1   5676-PTZX          No                          33          179   
2   8532-ZEKQ          No                          44           82   
3   1314-SMPJ          No                          10           47   
4   2956-TXCJ          No                          62          184   

   Local Mins  Intl Calls  Intl Mins Intl Active Intl Plan  \
0         8.0         0.0        0.0          No        no   
1       431.3         0.0        0.0          No        no   
2       217.6         0.0        0.0          No       yes   
3       111.6        60.0       71.0         Yes       yes   
4       621.2       310.0      694.4         Yes       yes   

   Extra International Charges  ...  Senior  Group  \
0                          0.0  ...      No     No   
1                          0.0  ...      No     No   
2                          0.0  ...      No     No   
3                          0.0  ...      No     No   
4                          0.0  ...      No     No   

  Number of Customers in Group  Device Protection & Online Backup  \
0                            0                                 No   
1                            0                                Yes   
2                            0                                Yes   
3                            0                                 No   
4                            0                                 No   

    Contract Type Payment Method Monthly Charge  Total Charges Churn Category  \
0  Month-to-Month   Direct Debit             10             10            NaN   
1        One Year    Paper Check             21            703            NaN   
2        One Year   Direct Debit             23           1014            NaN   
3  Month-to-Month    Paper Check             17            177            NaN   
4        One Year   Direct Debit             28           1720            NaN   

  Churn Reason  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 29 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6687 entries, 0 to 6686
Data columns (total 29 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Customer ID                        6687 non-null   object 
 1   Churn Label                        6687 non-null   object 
 2   Account Length (in months)         6687 non-null   int64  
 3   Local Calls                        6687 non-null   int64  
 4   Local Mins                         6687 non-null   float64
 5   Intl Calls                         6687 non-null   float64
 6   Intl Mins                          6687 non-null   float64
 7   Intl Active                        6687 non-null   object 
 8   Intl Plan                          6687 non-null   object 
 9   Extra International Charges        6687 non-null   float64
 10  Customer Service Calls             6687 non-null   int64  
 11  Avg Monthly GB Download            6687 non-null   int64

In [5]:
df.shape

(6687, 29)

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()[df.isnull().sum()>1]/len(df) *100

Churn Category    73.545686
Churn Reason      73.545686
dtype: float64

In [8]:
df['Churn Category'].unique()

array([nan, 'Competitor', 'Other', 'Attitude', 'Dissatisfaction', 'Price'],
      dtype=object)

In [9]:
df[df['Churn Category'].isnull()]['Churn Category'].isnull().sum()

4918

In [10]:
df[df['Churn Label'] == 'No'].shape

(4891, 29)

In [11]:
df[df['Churn Label'] == 'Yes'].shape

(1796, 29)

In [12]:
df[df['Churn Label'] == 'No']['Churn Category'].isnull().sum()

4891

In [13]:
df[df['Churn Label'] == 'Yes']['Churn Category'].value_counts(normalize=True, dropna=False) * 100

Churn Category
Competitor         44.821826
Attitude           15.979955
Dissatisfaction    15.924276
Price              11.135857
Other              10.634744
NaN                 1.503341
Name: proportion, dtype: float64

In [14]:
df[df['Churn Label'] == 'Yes']['Churn Reason'].value_counts(normalize=True, dropna=False) * 100

Churn Reason
Competitor made better offer                 16.870824
Competitor had better devices                16.536748
Attitude of support person                   11.302895
Don't know                                    6.848552
Competitor offered more data                  6.124722
Competitor offered higher download speeds     5.289532
Attitude of service provider                  4.677060
Price too high                                4.120267
Product dissatisfaction                       4.064588
Network reliability                           3.841871
Long distance charges                         3.396437
Service dissatisfaction                       3.340757
Moved                                         2.449889
Extra data charges                            2.060134
Limited range of services                     1.948775
Poor expertise of online support              1.670379
Lack of affordable download/upload speed      1.559020
NaN                                           1.5033

In [15]:
# Filter rows where 'churn category' is 'Voluntary' and 'churn reason' is missing
mask = (df['Churn Label'] == 'Yes') & (df['Churn Reason'].isna())

In [16]:
# Drop the rows
df_cleaned = df[~mask]
df_cleaned.shape


(6660, 29)

In [17]:
df.shape

(6687, 29)

In [18]:
df_cleaned[df_cleaned['Churn Label'] == 'Yes']['Churn Reason'].value_counts(normalize=True, dropna=False) * 100

Churn Reason
Competitor made better offer                 17.128321
Competitor had better devices                16.789146
Attitude of support person                   11.475410
Don't know                                    6.953081
Competitor offered more data                  6.218202
Competitor offered higher download speeds     5.370266
Attitude of service provider                  4.748445
Price too high                                4.183154
Product dissatisfaction                       4.126625
Network reliability                           3.900509
Long distance charges                         3.448276
Service dissatisfaction                       3.391747
Moved                                         2.487281
Extra data charges                            2.091577
Limited range of services                     1.978519
Poor expertise of online support              1.695873
Lack of affordable download/upload speed      1.582815
Lack of self-service on Website               1.4697

In [19]:
df_cleaned[df_cleaned['Churn Label'] == 'No']['Churn Reason'].value_counts(normalize=True, dropna=False) * 100

Churn Reason
NaN    100.0
Name: proportion, dtype: float64

In [20]:
#The above result makes absolute sense since the missing values are all the active customers should have

In [21]:
df_cleaned.loc[:,'Churn Category'] = df_cleaned['Churn Category'].fillna('Not Churned')


In [22]:
df_cleaned.loc[:,'Churn Reason'] = df_cleaned['Churn Reason'].fillna('No Reason')

In [23]:
df_cleaned.isnull().sum()[df_cleaned.isnull().sum() > 0] 

Series([], dtype: int64)

In [24]:
df_cleaned['Gender'].nunique()

3

### Data Preprocessing and Transformation

In [25]:
df_cleaned.columns = df_cleaned.columns.str.lower()

In [26]:
df_cleaned.columns

Index(['customer id', 'churn label', 'account length (in months)',
       'local calls', 'local mins', 'intl calls', 'intl mins', 'intl active',
       'intl plan', 'extra international charges', 'customer service calls',
       'avg monthly gb download', 'unlimited data plan', 'extra data charges',
       'state', 'phone number', 'gender', 'age', 'under 30', 'senior', 'group',
       'number of customers in group', 'device protection & online backup',
       'contract type', 'payment method', 'monthly charge', 'total charges',
       'churn category', 'churn reason'],
      dtype='object')

**Since there's an age column, i'll drop under 30 and senior columns**

In [27]:
df_cleaned.drop(columns=['under 30', 'senior'], inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\3257213617.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop(columns=['under 30', 'senior'], inplace=True)


In [28]:
df_cleaned.shape

(6660, 27)

In [29]:
numeric_columns = df_cleaned.select_dtypes('number').columns.to_list()

In [31]:
cols_with_less_than_6_values = []
def checkColumns_6Values(df):
    cat_columns = df.select_dtypes('object').columns.to_list()
    for col in cat_columns:
        if df[col].nunique() < 6:
            cols_with_less_than_6_values.append(col)
        else:
            continue

In [32]:
checkColumns_6Values(df_cleaned)

In [33]:
cols_with_less_than_6_values

['churn label',
 'intl active',
 'intl plan',
 'unlimited data plan',
 'gender',
 'group',
 'device protection & online backup',
 'contract type',
 'payment method']

In [34]:
cols_with_2_values = []
def checkColumns_2Values(df):
    cat_columns = df.select_dtypes('object').columns.to_list()
    for cols in cat_columns:
        if df[cols].nunique() == 2:
            cols_with_2_values.append(cols)
        else:
            continue

In [35]:
checkColumns_2Values(df_cleaned)

In [36]:
cols_with_2_values

['churn label',
 'intl active',
 'intl plan',
 'unlimited data plan',
 'group',
 'device protection & online backup']

In [37]:
df_cleaned[cols_with_2_values].head()

churn label intl active intl plan unlimited data plan group  \
0          No          No        no                 Yes    No   
1          No          No        no                 Yes    No   
2          No          No       yes                 Yes    No   
3          No         Yes       yes                 Yes    No   
4          No         Yes       yes                 Yes    No   

  device protection & online backup  
0                                No  
1                               Yes  
2                               Yes  
3                                No  
4                                No

#### **Check columns with Yes and No and replace them with 1 and 0, where 1 represents Yes and 0 represents No**

In [38]:
for col in cols_with_2_values:
    if df_cleaned[col].str.contains('yes', case=False).any():
        df_cleaned.loc[:,col] = df_cleaned[col].replace({"Yes":1, "No":0, "yes":1, "no":0})
        df_cleaned[col] = df_cleaned[col].astype("int")

C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\860080666.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[col] = df_cleaned[col].astype("int")
C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\860080666.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[col] = df_cleaned[col].astype("int")
C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\860080666.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] 

In [39]:
df_cleaned[cols_with_2_values]

churn label  intl active  intl plan  unlimited data plan  group  \
0               0            0          0                    1      0   
1               0            0          0                    1      0   
2               0            0          1                    1      0   
3               0            1          1                    1      0   
4               0            1          1                    1      0   
...           ...          ...        ...                  ...    ...   
6682            1            0          0                    1      1   
6683            1            0          0                    1      1   
6684            1            0          0                    1      1   
6685            1            0          0                    1      1   
6686            1            0          0                    0      1   

      device protection & online backup  
0                                     0  
1                                     1  
2                                     1  
3                                     0  
4                                     0  
...                                 ...  
6682                                  0  
6683                                  1  
6684                                  1  
6685                                  0  
6686                                  0  

[6660 rows x 6 columns]

In [40]:
cat_columns = df_cleaned.select_dtypes('object').columns.to_list()

In [41]:
cat_columns

['customer id',
 'state',
 'phone number',
 'gender',
 'contract type',
 'payment method',
 'churn category',
 'churn reason']

In [42]:
df_cleaned[cat_columns].columns

Index(['customer id', 'state', 'phone number', 'gender', 'contract type',
       'payment method', 'churn category', 'churn reason'],
      dtype='object')

In [43]:
df_cleaned['gender'].unique()

array(['Female', 'Male', 'Prefer not to say'], dtype=object)

In [44]:
#Male - 1, female - 2, prefer not to say - 0
df_cleaned['gender'] = df_cleaned['gender'].replace({"Male":1, "Female":2, "Prefer not to say":0})

C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\3962339055.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['gender'] = df_cleaned['gender'].replace({"Male":1, "Female":2, "Prefer not to say":0})


In [45]:
df_cleaned['gender'].unique()

array([2, 1, 0], dtype=int64)

In [46]:
df_cleaned['contract type'].unique()

array(['Month-to-Month', 'One Year', 'Two Year'], dtype=object)

In [47]:
#'Month-to-Month':0, 'One Year':1, 'Two Year':2
df_cleaned['contract type'].replace({'Month-to-Month':0, 'One Year':1, 'Two Year':2}, inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\3670342255.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['contract type'].replace({'Month-to-Month':0, 'One Year':1, 'Two Year':2}, inplace=True)


In [48]:
df_cleaned['contract type'].unique()

array([0, 1, 2], dtype=int64)

In [49]:
df_cleaned['contract type'].value_counts(dropna=False)

contract type
0    3400
2    1791
1    1469
Name: count, dtype: int64

In [50]:
df_cleaned['payment method'].unique()

array(['Direct Debit', 'Paper Check', 'Credit Card'], dtype=object)

In [51]:
df_cleaned['payment method'].replace({'Direct Debit':0, 'Paper Check':1, 'Credit Card':2}, inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\2090962341.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['payment method'].replace({'Direct Debit':0, 'Paper Check':1, 'Credit Card':2}, inplace=True)


In [52]:
df_cleaned['payment method'].unique()

array([0, 1, 2], dtype=int64)

In [53]:
df_cleaned['churn category'].unique()

array(['Not Churned', 'Competitor', 'Other', 'Attitude',
       'Dissatisfaction', 'Price'], dtype=object)

In [54]:
df_cleaned['churn category'].replace({'Not Churned':0, 'Competitor':1, 'Attitude':2, 'Dissatisfaction':3, 'Price':4, 'Other':5}, inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_3076\2881075456.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['churn category'].replace({'Not Churned':0, 'Competitor':1, 'Attitude':2, 'Dissatisfaction':3, 'Price':4, 'Other':5}, inplace=True)


In [55]:
df_cleaned['churn category'].unique()

array([0, 1, 5, 2, 3, 4], dtype=int64)

In [56]:
df_cleaned.select_dtypes('object').columns

Index(['customer id', 'state', 'phone number', 'churn reason'], dtype='object')

In [57]:
df_features = df_cleaned.drop(columns = 'churn reason')

In [58]:
df_features = df_cleaned.select_dtypes('number')

In [59]:
df_features.head()

churn label  account length (in months)  local calls  local mins  \
0            0                           1            3         8.0   
1            0                          33          179       431.3   
2            0                          44           82       217.6   
3            0                          10           47       111.6   
4            0                          62          184       621.2   

   intl calls  intl mins  intl active  intl plan  extra international charges  \
0         0.0        0.0            0          0                          0.0   
1         0.0        0.0            0          0                          0.0   
2         0.0        0.0            0          1                          0.0   
3        60.0       71.0            1          1                          0.0   
4       310.0      694.4            1          1                          0.0   

   customer service calls  ...  gender  age  group  \
0                       0  ...       2   35      0   
1                       0  ...       1   49      0   
2                       0  ...       1   51      0   
3                       0  ...       2   41      0   
4                       0  ...       1   51      0   

   number of customers in group  device protection & online backup  \
0                             0                                  0   
1                             0                                  1   
2                             0                                  1   
3                             0                                  0   
4                             0                                  0   

   contract type  payment method  monthly charge  total charges  \
0              0               0              10             10   
1              1               1              21            703   
2              1               0              23           1014   
3              0               1              17            177   
4              1               0              28           1720   

   churn category  
0               0  
1               0  
2               0  
3               0  
4               0  

[5 rows x 23 columns]

In [60]:
cols = df_features.columns.to_list()
cols.remove('churn label')

In [64]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6660 entries, 0 to 6686
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   churn label                        6660 non-null   int32  
 1   account length (in months)         6660 non-null   int64  
 2   local calls                        6660 non-null   int64  
 3   local mins                         6660 non-null   float64
 4   intl calls                         6660 non-null   float64
 5   intl mins                          6660 non-null   float64
 6   intl active                        6660 non-null   int32  
 7   intl plan                          6660 non-null   int32  
 8   extra international charges        6660 non-null   float64
 9   customer service calls             6660 non-null   int64  
 10  avg monthly gb download            6660 non-null   int64  
 11  unlimited data plan                6660 non-null   int32  
 1

In [67]:
df_features['churn category'].unique()

array([0, 1, 5, 2, 3, 4], dtype=int64)

In [101]:
X = df_features.drop(['churn label', 'churn category', 'gender'], axis=1)
y = df_features['churn label']

In [102]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import pickle

In [162]:
# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define the models and their respective parameter grids for tuning
models = {
    'Logistic Regression (Elastic Net)': {
        'model': LogisticRegression(solver='saga', penalty='elasticnet', max_iter=200, random_state=42),
        'params': {
            'C': [0.01, 0.1, 1, 10],
            'l1_ratio': [0.3, 0.5, 0.7]
        }
    },
    'Random Forest': {
        'model': RandomForestClassifier(random_state=42),
        'params': {
            'n_estimators': [50, 100, 150],
            'max_depth': [5, 10, 20],
            'min_samples_split': [2, 5, 10]
        }
    },
    'XGBoost': {
        'model': XGBClassifier(random_state=42),
        'params': {
            'n_estimators': [50, 100, 150],
            'max_depth': [5, 10, 20],
            'learning_rate': [0.01, 0.1, 0.2]
        }
    }
}

# Train and evaluate each model using a loop
best_models = {}
for name, model_info in models.items():
    print(f"Training and tuning {name}...")
    
    # Grid search for hyperparameter tuning
    grid_search = GridSearchCV(model_info['model'], model_info['params'], cv=5, scoring='accuracy', verbose=1)
    grid_search.fit(X_train, y_train)
    
    # Best model after tuning
    best_model = grid_search.best_estimator_
    best_models[name] = best_model
    
    # Predictions
    y_pred = best_model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, best_model.predict_proba(X_test)[:, 1])
    
    print(f"\n{name} Performance:")
    print(f"Best Parameters: {grid_search.best_params_}")
    print(f"Accuracy: {accuracy:.2f}")
    print(f"ROC-AUC: {roc_auc:.2f}")
    print(classification_report(y_test, y_pred))
    print("-" * 50)

# Compare the best models based on accuracy and ROC-AUC
print("\nSummary of Best Models:")
for name, model in best_models.items():
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
    
    print(f"{name} -> Accuracy: {accuracy:.2f}, ROC-AUC: {roc_auc:.2f}")

Training and tuning Logistic Regression (Elastic Net)...
Fitting 5 folds for each of 12 candidates, totalling 60 fits

Logistic Regression (Elastic Net) Performance:
Best Parameters: {'C': 0.1, 'l1_ratio': 0.3}
Accuracy: 0.88
ROC-AUC: 0.94
              precision    recall  f1-score   support

           0       0.91      0.94      0.93      1519
           1       0.79      0.71      0.75       479

    accuracy                           0.88      1998
   macro avg       0.85      0.82      0.84      1998
weighted avg       0.88      0.88      0.88      1998

--------------------------------------------------
Training and tuning Random Forest...
Fitting 5 folds for each of 27 candidates, totalling 135 fits

Random Forest Performance:
Best Parameters: {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100}
Accuracy: 0.90
ROC-AUC: 0.95
              precision    recall  f1-score   support

           0       0.92      0.96      0.94      1519
           1       0.85      0.73    

In [104]:
best_models

{'Logistic Regression (Elastic Net)': LogisticRegression(C=0.1, l1_ratio=0.3, max_iter=200, penalty='elasticnet',
                    random_state=42, solver='saga'),
 'Random Forest': RandomForestClassifier(max_depth=10, random_state=42),
 'XGBoost': XGBClassifier(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=0.1, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=5, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               multi_strategy=None, n_estimators=100, n_jobs=None,
               num_parallel_tree=None, random_st

In [110]:
best_XGB = best_models['XGBoost']

In [111]:
with open('best_XGB_model.pkl', 'wb') as f:
    pickle.dump(best_XGB, f)